In [2]:
import ctypes
import numpy as np
import math
import time

#Define point structure
class HeliosPoint(ctypes.Structure):
    #_pack_=1
    _fields_ = [('x', ctypes.c_uint16),
                ('y', ctypes.c_uint16),
                ('r', ctypes.c_uint8),
                ('g', ctypes.c_uint8),
                ('b', ctypes.c_uint8),
                ('i', ctypes.c_uint8)]
class Dac:
    def __init__(self):
        #Load and initialize library
        self.HeliosLib = ctypes.cdll.LoadLibrary("./libHeliosDacAPI.so")
        self.num_devices = self.HeliosLib.OpenDevices()
        print("Found ", self.num_devices, "Helios DACs")
        # Define limits
        self.xy_max = int(2**12-1)

class DacQueue:
    '''
    A queue for patterns sent to the dac. 
    Performs smart stitching between patterns.
    '''
    def __init__(self):
        # Dac object for this queue
        self.dac = Dac()
        # The last position of the last pattern (x,y)
        self.last_pos = (0,0)
        # Sample rate of the DAC
        self.dac_rate = 55000
        # Debugging dac rate
        #self.debug_rate = 550
        self.debug_rate = 150
        
    
    def submit(self, pat_pos, pat_col, angular_density=100, debug=False):
        '''
        Submits a new pattern to the dac, transitioning smoothly from the last one.
        Angular density describes how many points per radian should be used to transition
        '''
        # Make the transition
        dist = np.sqrt(np.sum(np.power(self.last_pos-pat_pos[0,:], 2)))
        num_gap_points = int(dist*angular_density)

        gap_pos = np.linspace(self.last_pos, pat_pos[0,:], num_gap_points, dtype=np.float)
        gap_col = np.zeros((num_gap_points, 3), dtype=np.float)
        if(debug):
            gap_col = np.ones_like(gap_col)/4

        # Prep the transition pattern
        gap_points, num_gap_points = self.prep_pattern(gap_pos, gap_col, gap=True)
        
        # Prep the new pattern
        pat_points, num_pat_points = self.prep_pattern(pat_pos, pat_col)
        
        # Send the transition pattern to the dac
        self.write_frames(gap_points, num_gap_points, do_not_loop=True, debug=debug)
        # Send the new pattern to the dac
        self.write_frames(pat_points, num_pat_points, do_not_loop=True, debug=debug)
        # Set the last_position
        self.last_pos = pat_pos[-1, :].copy()
        
    def prep_pattern(self, arr_pos, arr_col, gap=False):
        '''
        1) Scales and color corrects 
        2) Converts from unit space to DAC coordinates
        3) Produces a DAC compatible frame and displays it
        '''
        # Force pass-by-value
        arr_pos = arr_pos.copy()
        arr_col = arr_col.copy()
        # Scale the pattern 
        arr_pos = position_corection(arr_pos)
        # Format the position array (-1.0-1.0) -> int(0-4095)
        arr_pos = (((arr_pos+1)/2.0)*self.dac.xy_max).astype(np.int32)

        # Perform color correction if not gap points
        if(not gap):
            arr_col = color_correction(arr_col)
        # Format the color array (0-1.0) -> int(0-255)
        arr_col = (arr_col*255).astype(np.int32)
        # Fill a heliospoint arr with these values
        num_points = len(arr_pos)

        frameType = HeliosPoint * num_points
        points = frameType()
        # Fill the frame
        for idx in range(num_points):
            points[idx] =     HeliosPoint(int(arr_pos[idx, 0]), 
                                         int(arr_pos[idx, 1]), 
                                         int(arr_col[idx, 0]), 
                                         int(arr_col[idx, 1]),
                                         int(arr_col[idx, 2]),
                                         int(255))
        
        return points, num_points
            
    def write_frames(self, points, num_points, do_not_loop=False, start_immediately=False, debug=False):
        if(num_points < 1):
            return
        # Write the values out 
        status_attempts = 0
        max_attempts = np.inf
        # Make 512 attempts for DAC status to be ready. After that, just give up and try to write the frame anyway
        while(status_attempts < max_attempts and self.dac.HeliosLib.GetStatus(0) != 1):
            status_attempts += 1
            
        # Create flags 
        flags = do_not_loop << 1 | start_immediately << 0
        # Send to DAC
        frame_rate = self.debug_rate if debug else self.dac_rate
        self.dac.HeliosLib.WriteFrame(0, frame_rate, flags, ctypes.pointer(points), num_points)

def color_correction(arr_color):
    '''
    Corrects the nonlinearities in the color curve 
    '''
    non_zero = arr_color > 0
    # Scale to the lower cutoff (R, G, B)
    lower_cutoff = np.array([0.25, 0.09, 0.09])
    arr_color = arr_color*(1-lower_cutoff) + lower_cutoff
    
    # Cutoff any zeros to ensure real black
    arr_color *= non_zero
    
    return arr_color

def position_corection(arr_pos):
    '''
    Corrects x-y directions so that (x=-1,y=-1) is bottom left
    Scales the entire pattern so that it does not clip (amps are weird)
    '''
    # Reverse direction of x and y
    arr_pos *= -1
    
    max_scale = 0.75
    return arr_pos*max_scale
    
def make_circular(arr_pos, arr_color):
    return np.concatenate([arr_pos, arr_pos[::-1, :]]), np.concatenate([arr_color, arr_color[::-1, :]])

def connect_in_space(arr_pos_list, angular_density=100, wait_per=None):
    '''
    Given a list of position arrays, produce a list of array positions that are connected
    '''
    new_arr_pos_list = []
    for i in range(len(arr_pos_list)-1):
        # Get start/end positions for this gap
        pos_start = arr_pos_list[i][-1, :].copy()
        pos_end = arr_pos_list[i+1][ 0, :].copy()
        
        # Make the transition
        dist = np.sqrt(np.sum(np.power(pos_start-pos_end, 2)))
        num_gap_points = int(dist*angular_density)
        gap_pos = np.linspace(pos_start, pos_end, num_gap_points, dtype=np.float)
        
        # If we have a wait period, add it to the end of the gap positions
        if(wait_per):
            rep_bef = np.repeat(pos_start[np.newaxis, :], wait_per, axis=0)
            rep_aft = np.repeat(pos_end[np.newaxis, :], wait_per, axis=0)
            gap_pos = np.concatenate([rep_bef, gap_pos, rep_aft])
            
        
        new_arr_pos_list.append(arr_pos_list[i])
        new_arr_pos_list.append(gap_pos.copy())
    new_arr_pos_list.append(arr_pos_list[-1])
    
    return new_arr_pos_list

def fixed_interp(points, n_interp_points):
    '''
    Expands a list of points to a position array where those 
    points are the anchors in a smooth trajectory. 
    There is a fixed number of interp points between 
    the given points. 
    Inputs: 
        points - (N,2) - list of anchor points
        n_interp_points - number of points between anchors
    '''
    interped_pos_arr = []
    for i in range(len(points)-1):
        p1 = points[i]
        p2 = points[i+1]
        gap_pos = np.linspace(p1, p2, n_interp_points)
        interped_pos_arr += [p1]
        interped_pos_arr += [gap_pos]
    interped_pos_arr += [p2]
    
    # Convert them into one array 
    interped_pos_arr = np.concatenate(interped_pos_arr, axis=0)
    return interped_pos_arr
    


In [3]:
queue = DacQueue()

Found  1 Helios DACs


In [3]:
# Produce slow circles 
T = 1000
freq = 1.0/100.0
color_arr = np.ones((T,3))/10
start_ang = 0

while(True):
    theta = np.linspace(start_ang, start_ang+2*np.pi, T)
    pos_arr = np.zeros((T, 2))
    pos_arr[:, 0] = np.cos(freq*theta)
    pos_arr[:, 1] = np.sin(freq*theta)
    queue.submit(pos_arr, color_arr)
    start_ang += 2*np.pi

KeyboardInterrupt: 

In [5]:
# Produce colored circles 
T = 1000
theta = np.linspace(0, 2*np.pi, T)
pos_arr = np.zeros((T, 2))
pos_arr[:, 0] = np.cos(theta)
pos_arr[:, 1] = np.sin(theta)

start = (0.1, 1.0, 0.1)
finish = (1.0, 0.1, 1.0)
smooth = np.linspace(start, finish, T//2)

color_arr = np.concatenate([smooth, smooth[::-1]])/4

for i in range(100):
    queue.submit(pos_arr, color_arr)


In [9]:
# Produce a SINE wave
T = 1000
theta = np.linspace(0, 2*np.pi, T)
freq = 3
pos_arr = np.zeros((T, 2))
pos_arr[:, 0] = np.linspace(-1.0, 1.0, T)
pos_arr[:, 1] = np.sin(theta*freq)

start = (0.0, 0.0, 1.0)
finish = (1.0, 0.0, 1.0)
smooth = np.linspace(start, finish, T)

color_arr = np.concatenate([smooth, smooth[::-1]])/4

for i in range(100):
    queue.submit(pos_arr, color_arr, debug=False)


In [8]:
# Produce a phase shifting sine wave
T = 600
freq = 4
pos_arr = np.zeros((T, 2))
pos_arr[:, 0] = np.linspace(-1.0, 1.0, T)
start = (0.0, 0.0, 1.0)
finish = (1.0, 1.0, 1.0)
smooth = np.linspace(start, finish, T)

color_arr = np.concatenate([smooth, smooth[::-1]])/4

for i in range(10):
    for phi in np.linspace(0, 2*np.pi, 100):
        theta = np.linspace(phi, phi+2*np.pi, T)

        pos_arr[:, 1] = np.sin(theta*freq)

        queue.submit(pos_arr, color_arr, debug=False)


In [10]:
# Produce a double SINE wave
T = 1000
theta = np.linspace(0, 4*np.pi, T)
freq = 3
pos_arr = np.zeros((T, 2))
pos_arr[:, 0] = np.concatenate([np.linspace(-1.0, 1.0, T//2), np.linspace(1.0, -1.0, T//2)])
pos_arr[:, 1] = np.sin(theta*freq)

start = (0.0, 0.0, 1.0)
finish = (1.0, 0.0, 1.0)
smooth = np.linspace(start, finish, T)

color_arr = np.concatenate([smooth, smooth[::-1]])/4

for i in range(100):
    queue.submit(pos_arr, color_arr, debug=False)


In [14]:
# Produce a modulated wave
T = 1000
theta = np.linspace(0, 4*np.pi, T)
pos_arr = np.zeros((T, 2))
pos_arr[:, 0] = np.concatenate([np.linspace(-1.0, 1.0, T//2), np.linspace(1.0, -1.0, T//2)])
start = (0.0, 0.0, 1.0)
finish = (1.0, 0.0, 1.0)
smooth = np.linspace(start, finish, T)

color_arr = np.concatenate([smooth, smooth[::-1]])/4
for i in range(3):
    for freq in np.linspace(1, 4, 200):
        pos_arr[:, 1] = np.sin(theta*freq)
        queue.submit(pos_arr, color_arr, debug=False)


In [147]:
# Make a white fan with colored beams in it

beam_dwell = 50
n_beams = 6
beam_col = (0.0, 1.0, 0.0)
fan_col = np.array((1.0, 1.0, 1.0))/4

beam_positions = np.linspace(-1, 1, n_beams)
beams = []
for pos in beam_positions:
    beam = np.zeros((beam_dwell, 2))
    beam[:, 0] = pos
    beams.append(beam.copy())

beam_fan_list = connect_in_space(beams, wait_per=10)
color_arrs = []
for idx,pat in enumerate(beam_fan_list):
    if(idx % 2 == 0):
        color_arrs.append(np.ones((pat.shape[0], 3))*beam_col)
    else:
        color_arrs.append(np.ones((pat.shape[0], 3))*fan_col)
        
pos_arr = np.concatenate(beam_fan_list, axis=0)
col_arr = np.concatenate(color_arrs, axis=0)

pos_arr, col_arr = make_circular(pos_arr, col_arr)

offset_arr = np.zeros_like(pos_arr) 
for i in range(4):
    for y_pos in np.concatenate([np.linspace(-1, 1, 30), np.linspace(1, -1, 60)]):
        offset_arr[:, 1] = y_pos
        queue.submit(pos_arr+offset_arr, col_arr, debug=False)

KeyboardInterrupt: 

In [148]:
# Make a white cone with colored beams in it

beam_dwell = 50
n_beams = 6
beam_col = (0.0, 1.0, 0.0)
fan_col = np.array((1.0, 1.0, 1.0))/4

thetas = np.linspace(0, 2*np.pi, n_beams)
beam_positions = np.stack([np.cos(thetas), np.sin(thetas)], axis=1)
beams = []
for pos in beam_positions:
    beam = np.zeros((beam_dwell, 2))
    beam[:, 0:2] = pos
    beams.append(beam.copy())

beam_fan_list = connect_in_space(beams, wait_per=10)
color_arrs = []
for idx,pat in enumerate(beam_fan_list):
    if(idx % 2 == 0):
        color_arrs.append(np.ones((pat.shape[0], 3))*beam_col)
    else:
        color_arrs.append(np.ones((pat.shape[0], 3))*fan_col)
        
pos_arr = np.concatenate(beam_fan_list, axis=0)
col_arr = np.concatenate(color_arrs, axis=0)

for i in range(100):
    for y_pos in np.concatenate([np.linspace(-1, 1, 2), np.linspace(1, -1, 2)]):
        queue.submit(pos_arr, col_arr, debug=False)

In [152]:
# Make a white cone with colored beams in it that randomly mutates
beam_dwell = 50
n_beams = 3
beam_col = (0.0, 1.0, 0.0)
fan_col = np.array((1.0, 1.0, 1.0))/8

def normalize_color(color):
    d = math.sqrt(np.sum(color**2))
    return color/d

T = 1000
theta = np.linspace(0, 2*np.pi, T)
pos_arr = np.zeros((T, 2))
pos_arr[:, 0] = np.cos(theta)
pos_arr[:, 1] = np.sin(theta)

thetas = np.linspace(0, 2*np.pi, n_beams+1)
beam_positions = np.stack([np.cos(thetas), np.sin(thetas)], axis=1)
beams = []
for pos in beam_positions:
    beam = np.zeros((beam_dwell, 2))
    beam[:, 0:2] = pos
    beams.append(beam.copy())
beam_fan_list = connect_in_space(beams, wait_per=10)

pattern_size = 0.8
steps = 10000
ang = 0
for step in range(steps):
    ang += 0.01*np.pi
    rot_mat = np.array([[np.cos(ang), -np.sin(ang)], 
                        [np.sin(ang), np.cos(ang)]])
    
    rnd = 0.1*(np.random.rand(3)-0.5)
    beam_col += rnd
    beam_col = np.clip(beam_col, 0, 1)
    beam_col = normalize_color(beam_col)
    color_arrs = []
    for idx,pat in enumerate(beam_fan_list):
        if(idx % 2 == 0):
            color_arrs.append(np.ones((pat.shape[0], 3))*beam_col)
        else:
            color_arrs.append(np.ones((pat.shape[0], 3))*fan_col)

    pattern_size = np.clip(pattern_size + ((np.random.rand(1) > 0.5).astype(np.float32)-0.5)/20, 0.2, 1.0) 
    pos_arr = np.concatenate(beam_fan_list, axis=0)
    col_arr = np.concatenate(color_arrs, axis=0)
    queue.submit(pattern_size*np.matmul(pos_arr, rot_mat), col_arr, debug=False)

KeyboardInterrupt: 

In [1]:
# Circle w/ a spike
T = 1000
theta = np.linspace(0, 2*np.pi, T)
pos_arr = np.zeros((T, 2))
pos_arr[:, 0] = np.cos(theta)
pos_arr[:, 1] = np.sin(theta)
start = (0.0, 0.0, 1.0)
finish = (1.0, 0.0, 1.0)
smooth = np.linspace(start, finish, T//2)
color_arr = np.concatenate([smooth, smooth[::-1]])/4

spike_freq = 20
for i in range(T):
    pos_copy = pos_arr.copy()
    p = (spike_freq*i)%T
    pos_copy[int(p), :] = 0
    queue.submit(pos_copy, color_arr, debug=False)

NameError: name 'np' is not defined

In [ ]:
np.matmul(np.zeros((T,2)), np.zeros((2,2))).shape

In [ ]:
# Make a smart circle that maps color and radius to some input

# Dynamic range of r
min_r = 0.8
max_r = 1.0
# Correspond to the freq components to visualize
bins = 16
T = 1000
theta = np.linspace(np.pi/2, np.pi/2+2*np.pi, 2*T)

col_arr = np.array((0.5, 0.2, 1.0))[np.newaxis, :]

# Perform the loop 
for i in range(1000):
    # Since we don't have sound input, make it up 
    if(i%200 == 0):
        freq_hist = np.random.rand(bins)*(max_r-min_r) + min_r
        interp_len = int((T-bins)/(bins+1) + 1)
        #r = fixed_interp(freq_hist, n_interp_points=interp_len)[0:T]
        # The array holding the radius of the circle at an angle
        r = np.repeat(freq_hist, T//bins+1)[0:T]
        # Make symmetric
        r = np.concatenate([r, r[::-1]])
    

    
    pos_arr = np.zeros((2*T, 2))
    pos_arr[:, 0] = r*np.cos(theta)
    pos_arr[:, 1] = r*np.sin(theta)
    queue.submit(pos_arr, col_arr*np.ones((2*T, 3)), debug=False)




In [ ]:
freq_hist = np.random.rand(bins)*(max_r-min_r) + min_r
# Find the positions of the components in the circle
r_positions = np.linspace(np.pi/2, np.pi/2+2*np.pi, bins+1, endpoint=False) + 1/(2*(bins+1))
pos = np.stack([np.sin(r_positions), np.sin(r_positions)], axis=1)
fixed_interp(pos, 10)

In [ ]:
np.repeat(freq_hist, 100)[0:T].shape


In [ ]:
# Make a tri-colored circle
# Make a tricolor circle
T = 1000
pos_arr = np.zeros((T, 2))
col_arr = np.zeros((T, 3))

# Set Xs and Ys
theta = np.linspace(0, 2*np.pi, T)
pos_arr[:,0] = np.cos(theta)
pos_arr[:,1] = np.sin(theta)


# Tri color the circle
col_arr[theta < np.pi, 0] = 0
col_arr[theta < np.pi, 1] = 0
col_arr[theta < np.pi, 2] = 0.3
col_arr[theta < (2/3)*np.pi, 0] = 0
col_arr[theta < (2/3)*np.pi, 1] = 0.3
col_arr[theta < (2/3)*np.pi, 2] = 0
col_arr[theta < (1/3)*np.pi, 0] = 0.3
col_arr[theta < (1/3)*np.pi, 1] = 0
col_arr[theta < (1/3)*np.pi, 2] = 0

for i in range(100):
    queue.submit(pos_arr, color_arr)


In [ ]:
scales = np.concatenate([np.linspace(1.0, 0.5, 10), np.linspace(0.5, 1, 20)])

import time
while(True):
    for scale in scales:
        new_pos_arr = scale*pos_arr
        queue.submit(new_pos_arr, col_arr)
    break


In [43]:
import cv2
def draw_bitmap(arr_pos, arr_color, dims=(400,400)):
    '''
    Draws a pattern as if we were drawing it on a wall
    '''
    # Copy the arrays so we don't change them 
    arr_pos = arr_pos.copy()
    arr_color = arr_color.copy()
    # Map the positions
    arr_pos[:,0] *= -1
    arr_pos = (((arr_pos+1)/2)*dims).astype(np.int)
    # Map the colors
    arr_color = arr_color[:,::-1]
    T = len(arr_pos)
    img = np.zeros(dims+(3,))
    # Draw points
    for t in range(1, T):
        cv2.line(img, arr_pos[t-1], arr_pos[t], color=arr_color[t-1], thickness=2)
    cv2.imshow('img', img)
    cv2.waitKey(0)
    
    

In [ ]:
# Make three parallel lines
T_line = 100

arr_pos_list = []
arr_color_list = []
for c_idx, y in enumerate(range(-1, 2, 1)):
    arr_pos_list.append(np.stack([np.linspace(-1, 1, T_line), y*np.ones(T_line)], axis=1))
    arr_color = np.zeros((T_line, 3))
    arr_color[:, c_idx] = np.linspace(0, 1, T_line)
    arr_color_list.append(arr_color.copy())

for i in range(100):
    for arr_pos, arr_color in zip(arr_pos_list, arr_color_list):
        queue.submit(arr_pos, arr_color)

In [ ]:
# Make three concentric circles
T_line = 200
theta_line = np.linspace(0, 2*np.pi, T_line)

arr_pos_list = []
arr_color_list = []
for c_idx, scale in enumerate([0.9, 0.95, 1]):
    arr_pos_list.append(np.stack([np.cos(theta_line), np.sin(theta_line)], axis=1)/scale)
    arr_color = np.zeros((T_line, 3))
    arr_color[:, c_idx] = np.linspace(0, 1, T_line)
    arr_color_list.append(arr_color.copy())

for i in range(1000):
    for arr_pos, arr_color in zip(arr_pos_list, arr_color_list):
        queue.submit(arr_pos, arr_color)

In [ ]:
draw_bitmap(arr_pos, arr_color)

In [31]:
# make a sine wave
T = 500
freq = 4
theta_line = np.linspace(0, 2*np.pi, T)
arr_pos = np.stack([np.linspace(-1, 1, T), np.sin(freq*theta_line)], axis=1)
#arr_color = np.ones((T, 3))
arr_color = np.linspace((0.1, 1.0, 0.3), (1.0, 0.0, 0.7), T)
for i in range(100):
    queue.submit(arr_pos, arr_color, debug=False)

In [32]:
from skimage.color import rgb2lab, lab2rgb

In [95]:
print(lab2rgb((0,0,0)))
print(rgb2lab((0.10,0.10,0.255)))
print(rgb2lab((0.5,1,1)))
print('this: ', lab2rgb((10.0,-100.0, 10.0)))



l_lims = (0, 100)
a_lims = (-100, 100)
b_lims = (-100, 100)

w = a_lims[1] - a_lims[0] 
h = b_lims[1] - b_lims[0] 
img = np.zeros((h, w, 3), np.float32)

for a_idx, a in enumerate(np.linspace(*a_lims, h)):
    for b_idx, b in enumerate(np.linspace(*b_lims, w)):
        img[a_idx, b_idx, :] = lab2rgb((90.0, float(a), float(b)))

cv2.imshow('frame', img)
cv2.waitKey(0)

[0. 0. 0.]
[ 11.357263    13.5097441  -25.23433865]
[ 93.13904229 -35.33482179 -10.88977706]
this:  [0.         0.20535174 0.02948849]


106

In [97]:
lab2rgb(np.random.rand(100, 100, 3))

lab_img = 
cv2.imshow('f', lab2rgb(np.linspace((50, -127, 127))))

array([[[2.57922176e-02, 1.12165309e-02, 5.05683250e-03],
        [4.37358992e-03, 4.53428421e-04, 0.00000000e+00],
        [1.28798169e-02, 6.98422447e-03, 6.68063320e-03],
        ...,
        [1.74350785e-02, 1.08569837e-02, 6.70971081e-03],
        [1.33796085e-02, 0.00000000e+00, 0.00000000e+00],
        [1.33085430e-02, 6.00047213e-04, 0.00000000e+00]],

       [[2.48174935e-02, 7.14020560e-03, 2.06070348e-03],
        [1.46171200e-02, 8.27866722e-03, 3.34512197e-03],
        [1.38298105e-02, 0.00000000e+00, 0.00000000e+00],
        ...,
        [6.22313450e-03, 0.00000000e+00, 0.00000000e+00],
        [5.60586841e-03, 1.26265281e-03, 0.00000000e+00],
        [1.86176357e-02, 1.23693192e-02, 1.19535747e-02]],

       [[1.70000118e-02, 4.59894197e-03, 0.00000000e+00],
        [1.31644877e-02, 9.42564665e-03, 9.99510596e-03],
        [2.06500717e-02, 7.96139309e-03, 6.62717268e-03],
        ...,
        [1.20577795e-02, 8.82497700e-04, 0.00000000e+00],
        [2.50245896e-02, 9.28

In [ ]:
# Circles in the CIELAB Space
# UNFINISHED - see this for documentation: https://github.com/scikit-image/scikit-image/blob/main/skimage/color/colorconv.py#L1142-L1183
# Range is here? :https://stackoverflow.com/questions/25294141/cielab-color-range-for-scikit-image
scales = np.concatenate([np.linspace(1, 0.1, 200), np.linspace(0.1, 1, 200)])

T = 400


# Set Xs and Ys
theta = np.linspace(0, 2*np.pi, T)
arr_pos = np.zeros((T, 2))
arr_pos[:,0] = np.cos(theta)
arr_pos[:,1] = np.sin(theta)

# Set the colors 
arr_cols = []
for scale in scales:
    arr_col_lab = np.zeros((T, 3))
    # Set the luminosity to the scale
    #arr_col_lab[:, 0] = scale*100.0
    arr_col_lab[:, 0] = 10
    arr_col_lab[:, 1::] = 127.0*arr_pos/2.0
    arr_cols.append(lab2rgb(arr_col_lab))

for i in range(1000):
    for scale, arr_col in zip(scales, arr_cols):
        queue.submit(arr_pos*scale, arr_col)

    
    

In [110]:
img = np.zeros((10000, 10000, 2))
for row in range(10000):
    for col in range(10000):
        img[row, col] = row, col

KeyboardInterrupt: 

In [108]:
img.shape

(100, 100, 2)

In [128]:
N = 10
x = np.linspace(0, N-1, N)
y = np.linspace(0, N-1, N)
x = np.stack([x]*N, axis=1)
y = np.stack([y]*N, axis=0)
stacked = np.stack([x, y], axis=-1)

In [129]:
print(stacked)

[[[0. 0.]
  [0. 1.]
  [0. 2.]
  [0. 3.]
  [0. 4.]
  [0. 5.]
  [0. 6.]
  [0. 7.]
  [0. 8.]
  [0. 9.]]

 [[1. 0.]
  [1. 1.]
  [1. 2.]
  [1. 3.]
  [1. 4.]
  [1. 5.]
  [1. 6.]
  [1. 7.]
  [1. 8.]
  [1. 9.]]

 [[2. 0.]
  [2. 1.]
  [2. 2.]
  [2. 3.]
  [2. 4.]
  [2. 5.]
  [2. 6.]
  [2. 7.]
  [2. 8.]
  [2. 9.]]

 [[3. 0.]
  [3. 1.]
  [3. 2.]
  [3. 3.]
  [3. 4.]
  [3. 5.]
  [3. 6.]
  [3. 7.]
  [3. 8.]
  [3. 9.]]

 [[4. 0.]
  [4. 1.]
  [4. 2.]
  [4. 3.]
  [4. 4.]
  [4. 5.]
  [4. 6.]
  [4. 7.]
  [4. 8.]
  [4. 9.]]

 [[5. 0.]
  [5. 1.]
  [5. 2.]
  [5. 3.]
  [5. 4.]
  [5. 5.]
  [5. 6.]
  [5. 7.]
  [5. 8.]
  [5. 9.]]

 [[6. 0.]
  [6. 1.]
  [6. 2.]
  [6. 3.]
  [6. 4.]
  [6. 5.]
  [6. 6.]
  [6. 7.]
  [6. 8.]
  [6. 9.]]

 [[7. 0.]
  [7. 1.]
  [7. 2.]
  [7. 3.]
  [7. 4.]
  [7. 5.]
  [7. 6.]
  [7. 7.]
  [7. 8.]
  [7. 9.]]

 [[8. 0.]
  [8. 1.]
  [8. 2.]
  [8. 3.]
  [8. 4.]
  [8. 5.]
  [8. 6.]
  [8. 7.]
  [8. 8.]
  [8. 9.]]

 [[9. 0.]
  [9. 1.]
  [9. 2.]
  [9. 3.]
  [9. 4.]
  [9. 5.]
  [9. 6.]
  [9. 7.]
  

In [132]:
stacked[9, 1]

array([9., 1.])

In [16]:
# Random ellipses
T = 500
arr_col = np.ones((T, 3))
while(True):
    a = np.random.rand(1)
    b = np.random.rand(1)
    theta = np.linspace(0, 2*np.pi, T)
    arr_pos = np.zeros((T, 2))
    arr_pos[:,0] = a*np.cos(theta)
    arr_pos[:,1] = b*np.sin(theta)
    col_gate = np.repeat(np.random.rand(T//10, 3) > 0.2, 10, axis=0)
    for i in range(20):
        queue.submit(arr_pos, arr_col*col_gate)

    

KeyboardInterrupt: 

In [79]:
# Interpolated ellipses
T = 500
arr_col = np.ones((T, 3))
theta = np.linspace(0, 2*np.pi, T)

a_old = 1.0
b_old = 1.0
c_old = (1.0, 1.0, 1.0)
arr_pos = np.zeros((T, 2))
arr_pos[:,0] = np.cos(theta)
arr_pos[:,1] = np.sin(theta)
accel_max = math.sqrt((1-0)**2 + (1-0)**2)

T_trans = 5

while(True):
    a = np.random.rand(1)[0]
    b = np.random.rand(1)[0]
    c = np.random.rand(3)
    
    #col_gate = np.repeat(np.random.rand(T//10, 3) > 0.5, 10, axis=0)
    col_gate = 1
    ell_interp = np.linspace((a_old, b_old), (a, b), T_trans)
    col_interp = np.linspace(c_old, c, T_trans, axis=0)
    accel = math.sqrt((a_old-a)**2 + (b_old-b)**2)
    accel_norm = accel/accel_max

    for ell_inter, c_inter in zip(ell_interp, col_interp):
        queue.submit((ell_inter*arr_pos), np.repeat(c_inter[np.newaxis, :], T, axis=0))
        
    a_old = a
    b_old = b
    c_old = c

    

KeyboardInterrupt: 

In [84]:
# Interpolated ellipses with beamifier (dweller)
T = 500
arr_col = np.ones((T, 3))
theta = np.linspace(0, 2*np.pi, T)

a_old = 1.0
b_old = 1.0
c_old = (1.0, 1.0, 1.0)
arr_pos = np.zeros((T, 2))
arr_pos[:,0] = np.cos(theta)
arr_pos[:,1] = np.sin(theta)
accel_max = math.sqrt((1-0)**2 + (1-0)**2)

T_trans = 8

while(True):
    a = np.random.rand(1)[0]
    b = np.random.rand(1)[0]
    c = np.random.rand(3)
    
    ell_interp = np.linspace((a_old, b_old), (a, b), T_trans)
    col_interp = np.linspace(c_old, c, T_trans, axis=0)
    accel = math.sqrt((a_old-a)**2 + (b_old-b)**2)
    accel_norm = accel/accel_max

    
    for ell_inter, c_inter in zip(ell_interp, col_interp):
        arr_pos_inter = ell_inter*arr_pos
        c_arr = np.repeat(c_inter[np.newaxis, :], T, axis=0)
        #arr_pos_beam = beamify(arr_pos_inter, dwell=4)
        #queue.submit(arr_pos_beam, c_arr)
        queue.submit(arr_pos_inter, c_arr)
        
    a_old = a
    b_old = b
    c_old = c

    

KeyboardInterrupt: 

In [50]:
# Beamify
x = np.linspace(0, 1, 100)
x = np.repeat(x[::10], 10)

In [ ]:
def beamify(arr_pos, num_beams=4, dwell=20):
    '''
    NOT DONE - inserts spots in the trajectory where the beam stops and makes a solid beam
    '''
    T = arr_pos.shape[0]
    beam_idxs = np.linspace(0, T, num_points+2)[1:-1].astype(np.int)
    np.insert(arr_pos)
    return arr_pos

In [78]:
x = np.zeros(101)
num_points = 4
beam_idxs = np.linspace(0, x.shape[0], num_points+2)[1:-1].astype(np.int)

In [77]:
beam_idxs

array([20.2, 40.4, 60.6, 80.8])

In [18]:
def ellipser(scale_x=1, scale_y=1, f_x=1, f_y=1, T=500):
    '''
    Generates a pattern that is a function of ellipses 
    with parameters that can be interpolated between
    '''
    theta = np.linspace(0, 2*np.pi, T)
    arr_pos = np.zeros((T, 2))
    arr_pos[:,0] = scale_x*np.cos(f_x*theta)
    arr_pos[:,1] = scale_y*np.sin(f_y*theta)
    
    # Not sure what to do about color yet, let's make it white
    arr_col = np.ones((T, 3), np.float32)
    
    return arr_pos, arr_col


In [19]:
arr_pos, arr_col = ellipser()
print(arr_pos.shape, arr_col.shape)

(500, 2) (500, 3)


In [ ]:
# Interpolated ellipses
T = 1000
arr_col = np.ones((T, 3))
theta = np.linspace(0, 2*np.pi, T)

min_vals = np.array([0.8, 0.0, 1.0, 0.0])
max_vals = np.array([1.0, 0.4, 2.0, 4.0])
pat_point_old = (max_vals-min_vals)*np.random.rand(len(max_vals)) + min_vals


T_trans = 30

while(True):
    pat_point = max_vals*np.random.rand(len(max_vals))
    ell_interp = np.linspace(pat_point_old, pat_point, T_trans)
    print(pat_point)
    for (scale_x, scale_y, freq_x, freq_y) in ell_interp:
        arr_pos, arr_col = ellipser(scale_x, scale_y, freq_x, freq_y)
        queue.submit(arr_pos, arr_col)
        
    pat_point_old = pat_point

[0.94337161 0.0648898  1.49337694 0.25933402]
[0.62992498 0.08917639 0.16800722 1.71893362]
[0.92326386 0.03190176 0.96857665 2.96669048]
[0.36238476 0.06569894 0.62681681 3.68428046]
[0.76229053 0.26282532 0.68326264 2.56417902]
[0.85370327 0.23580124 0.02780411 1.24449432]
[0.901962   0.15149829 0.51073661 2.04967484]
[0.39312977 0.25513806 1.8430188  3.32464327]
[0.20184672 0.22329337 1.05968088 0.29306013]
[0.29332849 0.31583993 1.52482837 0.72766749]
[0.83140706 0.1661891  0.63986156 3.7971363 ]
[0.96660008 0.28836242 0.76999962 0.92684878]
[0.07798799 0.01609562 1.03368467 1.54474954]
[0.20949602 0.3865469  0.71475907 3.3368496 ]
[0.98598178 0.00884857 0.81231397 0.95467338]
[0.73007876 0.06311527 1.38838195 3.14599515]
[0.56249601 0.06811001 1.08326417 3.95435262]
[0.54082414 0.07132711 0.46113181 2.12017639]
[0.96698884 0.11884725 1.55410195 0.96883654]
[0.49843186 0.34428509 1.7626611  2.06009413]
[0.01035181 0.16667134 1.10198186 0.62874118]
[0.83258713 0.36122362 0.43394127 

[0.41652678 0.00877983 1.03778539 0.23659975]
[0.64135068 0.03955136 1.81261342 2.09914511]
[0.96038988 0.16177412 0.80780424 2.07694105]
[0.99864146 0.13689768 1.95466143 2.81212306]
[0.81983793 0.08810453 1.598703   1.41380599]
[0.7762202  0.09597632 1.82352047 2.01797604]
[0.87977448 0.0507465  0.2238357  3.51593887]
[0.00518464 0.36081162 0.42988643 0.5731544 ]
[0.33125756 0.00865651 0.07795665 0.87042798]
[0.9306956  0.18843207 1.72869706 1.07344765]
[0.77597968 0.28547397 0.76817881 2.58582774]
[0.4815818  0.17480151 1.04709373 2.5061793 ]
[0.35255062 0.23730772 1.75346284 1.62176867]
[0.44696172 0.09557707 1.35924413 2.60184747]
[0.85505643 0.0955485  0.48879599 0.34910649]
[0.82256107 0.11853339 1.88586189 2.3920932 ]
[0.2464627  0.29179519 1.39861169 1.04809642]
[0.82857548 0.33047219 0.87165923 3.80087137]
[0.68339956 0.30091352 1.78912113 2.91129596]
[0.84965234 0.34457174 0.50860787 1.0736582 ]
[0.83140206 0.36622276 0.74508512 3.59823866]
[0.54348092 0.19424615 1.85333151 

[0.22216208 0.15791784 1.1129164  2.66516653]
[0.64826533 0.3365745  0.59980607 1.38383897]
[0.64910528 0.19466579 0.53853311 0.30922028]
[0.92249033 0.36319989 0.84198268 1.13606418]
[0.73704565 0.1619446  1.44067199 2.17388576]
[0.41593505 0.14468002 1.21884134 2.61006547]
[0.60271709 0.10254662 0.20419178 2.75774201]
[0.69059121 0.16874618 0.33544084 0.84341317]
[0.78113064 0.12948449 0.58583585 2.33717832]
[0.20014883 0.23473348 1.59284974 0.14873225]
[0.50857507 0.37058753 0.96112864 0.61965823]
[0.9000768  0.19698626 0.32642837 1.67923382]
[0.0392963  0.2242684  1.72411783 3.95251913]
[0.57273455 0.24125549 0.58060724 1.9896153 ]
[0.01398958 0.03332619 1.42667414 3.92995198]
[0.50757594 0.18442294 1.06648642 3.42044844]
[0.21472439 0.24810917 0.74262743 1.78632301]
[0.09468872 0.20278047 1.24799958 0.16680011]
[0.25364711 0.06228811 0.57238582 0.35659883]
[0.54638047 0.2625674  1.50481948 3.41004659]
[0.18235815 0.2354953  1.53675201 0.58373574]
[0.38042988 0.33663603 1.92922128 

[0.10442704 0.30083634 0.88871572 2.64482758]
[0.14319757 0.2734125  1.06861775 0.10356856]
[0.80097184 0.16215368 1.17566601 0.46077837]
[0.54113006 0.31712617 0.59446637 0.64915694]
[0.82873201 0.03672293 0.46761573 3.10732997]
[0.3994094  0.02385212 1.9165135  1.16132069]
[0.70955424 0.3171982  0.16570088 3.78144342]
[0.98349407 0.07833486 1.38518106 3.95187588]
[0.76694057 0.00530788 1.37738223 1.44026425]
[0.46349682 0.36978819 1.651951   0.67833245]
[0.0933622  0.35043607 1.47527733 0.25686964]
[0.18026996 0.30369335 1.60328894 1.13954408]
[0.15052554 0.26849771 1.59875134 2.70636703]
[0.344025   0.03614627 0.80210457 2.76297578]
[0.86758082 0.2549658  1.39090143 2.92726388]
[0.55062816 0.34765739 0.01869816 0.42915136]
[0.57946448 0.11198283 0.69443759 0.98312394]
[0.47732471 0.36659207 0.8813767  0.44329551]
[0.91446687 0.36042331 0.01417918 3.02856542]
[0.04606957 0.37118774 1.38555476 3.12299886]
[0.56453812 0.37905691 1.37250052 2.33996986]
[0.47502291 0.100255   1.22319763 